### ISSUE TITLE
applyでエラーが発生します

### ISSUE THREAD

**Issue by moongift** [higanworks/sakurraform#4]
$ sakurraform plan apply

を実行すると、次のようなエラーが発生します。バージョンは0.0.7です。

```
$ sakurraform plan apply
defaultrouter already available as defaultrouter-042dde10-0d80-0133-1fc2-2c87a306e9b4
defaultrouter2 already available as defaultrouter2-0db37c20-0d80-0133-1fc2-2c87a306e9b4
Create new server server1
[fog][WARNING] Create Server
[fog][WARNING] Create Volume
/Users/nakatsugawa/.rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/middlewares/expects.rb:6:in `response_call': Expected([202]) <=> Actual(400 Bad Request) (Excon::Errors::BadRequest)
excon.error.response
  :body          => "{\"is_fatal\":true,\"serial\":\"cfd18a75996a6c38f4dfb52de8cad015\",\"status\":\"400 Bad Request\",\"error_code\":\"param_res_not_found\",\"error_msg\":\"\\u4e0d\\u9069\\u5207\\u306a\\u8981\\u6c42\\u3067\\u3059\\u3002\\u30d1\\u30e9\\u30e1\\u30fc\\u30bf\\u3067\\u6307\\u5b9a\\u3055\\u308c\\u305f\\u30ea\\u30bd\\u30fc\\u30b9\\u304c\\u5b58\\u5728\\u3057\\u307e\\u305b\\u3093\\u3002ID\\u3092\\u3054\\u78ba\\u8a8d\\u304f\\u3060\\u3055\\u3044\\u3002\"}"
  :headers       => {
    "Cache-Control"            => "no-cache"
    "Connection"               => "keep-alive"
    "Content-Length"           => "386"
    "Content-Type"             => "application/json; charset=UTF-8"
    "Date"                     => "Thu, 16 Jul 2015 08:25:04 GMT"
    "Pragma"                   => "no-cache, no-cache"
    "Server"                   => "nginx"
    "Status"                   => "400 Bad Request"
    "X-Content-Type-Options"   => "nosniff"
    "X-FRAME-OPTIONS"          => "DENY"
    "X-Sakura-Content-Length"  => "386"
    "X-Sakura-Proxy-Microtime" => "199928"
    "X-Sakura-Serial"          => "cfd18a75996a6c38f4dfb52de8cad015"
    "X-XSS-Protection"         => "1; mode=block"
  }
  :local_address => "192.168.0.141"
  :local_port    => 64934
  :reason_phrase => "Bad Request"
  :remote_ip     => "210.224.172.33"
  :status        => 400
  :status_line   => "HTTP/1.1 400 Bad Request\r\n"
	from /Users/nakatsugawa/.rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'
	from /Users/nakatsugawa/.rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/connection.rb:372:in `response'
	from /Users/nakatsugawa/.rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/connection.rb:236:in `request'
	from /Users/nakatsugawa/.rvm/gems/ruby-2.1.2/gems/fog-core-1.32.0/lib/fog/core/connection.rb:81:in `request'
	from /Users/nakatsugawa/.rvm/gems/ruby-2.1.2/gems/fog-sakuracloud-1.0.1/lib/fog/sakuracloud/volume.rb:43:in `request'
	from /Users/nakatsugawa/.rvm/gems/ruby-2.1.2/gems/fog-sakuracloud-1.0.1/lib/fog/sakuracloud/requests/volume/create_disk.rb:20:in `create_disk'
```

エラーメッセージのJSONをパースすると次のようになっています。

```
{"is_fatal"=>true, "serial"=>"da43c101ba28da1c33847cceb29bdfd4", "status"=>"400 Bad Request", "error_code"=>"param_res_not_found", "error_msg"=>"不適切な要求です。パラメータで指定されたリソースが存在しません。IDをご確認ください。"} 
```

sakuracloud/volume.rb#43で実行している際のパラメータは次のようになっていました。

```
{:headers=>{"Authorization"=>"Basic xxx"}, :expects=>[202], :method=>"POST", :path=>"/cloud/zone/is1b/api/cloud/1.1//disk", :body=>"{\"Disk\":{\"Name\":\"8947f933-6fde-4e8e-92ac-129562bf6c5d\",\"SourceArchive\":{\"ID\":\"112600321618\"},\"Plan\":{\"ID\":4}}}"}
```

0.0.6の時はそのまま動いていたのですが、何か仕様が変わっていますでしょうか？

**Comment by sawanoboly** [comment]
※ リクエストパラメータのAuthorizationをコメント編集させてもらいました。

とりあえず、バージョン0.0.7, 0.0.6ともに身に覚えが無い気がします。。。

https://rubygems.org/gems/sakurraform

一旦それは置いといて、レスポンスのメッセージからすると、ソースアーカイブが存在しないように見えますが、同じゾーンにありますか？

**Comment by moongift** [comment]
@sawanoboly 
うお、Basic認証のコード失礼しました。

generateした時の plan/server.yml 

```
    volume:
      diskplan: 4
      sourcearchive: 112600321618 <- 
```

これですね。たぶんこれがないんですね（昔はあったのかな？）。変更してみます！

**Comment by moongift** [comment]
@sawanoboly 

```
sourcearchive: 112500463685
```

に変更したら通りました、ありがとうございます！

**Comment by sawanoboly** [comment]
@moongift 確認ありがとうございます。

生成元のテンプレートが古かったですね、Gemを更新しておきました。
